- name: A simple playbook that prints to the screen
  hosts: all
  gather_facts: false
  connection: ansible.builtin.local

  vars_files:
  - "{{ playbook_dir }}/vars/playbook09_debug_vars.yml"

  tasks:
  - name: Print to the screen
    ansible.builtin.debug:
       msg: "intro to aap"

  - name: Print var from our var file
    ansible.builtin.debug:
       var: acmebank_var
